TesteApiConsume/Consumer/Models/ApiCall.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace Consumer.Models
{
    public static class ApiCall
    {
        public static HttpResponseMessage Get(string ApiUrl)
        {
            HttpClient client = new HttpClient();
            var response = client.GetAsync(ApiUrl).Result;
            return response;
        }



        public static string Post(string ApiUrl, string postData = "")
        {

            var request = (HttpWebRequest)WebRequest.Create(ApiUrl);
            var data = Encoding.ASCII.GetBytes(postData);
            request.Method = "POST";
            request.ContentType = "application/x-www-form-urlencoded";
            request.ContentLength = data.Length;
            using (var stream = request.GetRequestStream())
            {
                stream.Write(data, 0, data.Length);
            }
            var response = (HttpWebResponse)request.GetResponse();
            var responseString = new StreamReader(response.GetResponseStream()).ReadToEnd();
            return responseString;
        }
    }
}

TesteApiConsume/Consumer/Models/ErrorViewModel.cs
using System;

namespace Consumer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TesteApiConsume/Consumer/Controllers/HomeController.cs
using API.Models;
using Consumer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Consumer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Pessoas()
        {
            var response = ApiCall.Get("https://localhost:44391/api/Pessoas");
            List<Pessoa> pessoas = JsonConvert.DeserializeObject<List<Pessoa>>(response.Content.ReadAsStringAsync().Result);
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TesteApiConsume/Consumer/Controllers/PessoasController.cs
using API.Models;
using Consumer.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using Consumer.Views.Pessoas;

namespace Consumer.Controllers
{
    public class PessoasController : Controller
    {
     
        public IActionResult Index()
        {
            //var response = ApiCall.Get("https://localhost:44364/api/Pessoas");
            ////List<Pessoa> pessoas = JsonConvert.DeserializeObject<List<Pessoa>>(response.Content.ReadAsStringAsync().Result);
            //var a = response.Content.ReadAsStringAsync().Result;
            return View();
        }
    }
}

TesteApiConsume/Consumer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    
</div>

TesteApiConsume/Consumer/Views/Pessoas/Index.cshtml
@page
@using API.Models;
@model IEnumerable<API.Models.Pessoa>
@{
}
<div class="text-center">
    @foreach (var pessoa in Model)
    {
        <h6>Nome:</h6>
        <h6>@pessoa.Name</h6>
        <br />
        <h6>Cpf:</h6>
        <h6>@pessoa.Cpf</h6>
        <br />
        <h6>Endereco:</h6>
        <h6>@pessoa.Adress</h6>
        <br />
        <h6>Genero:</h6>
        <h6>@pessoa.Gender</h6>
        <hr />
    }
</div>

TesteApiConsume/Consumer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Consumer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Consumer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoas" asp-action="Index">Pessoas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Consumer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>